server:
  port: 5555

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

zuul:
#  ignored-services: '*' # The ignored-services attribute is set to * to exclude the registration of all eureka service ID based routes
  prefix:  /api
  routes:
    # Your organizationservice and licensingservice are mapped to the organization and licensing endpoints respectively
    organizationservice: /organization/**
    licensingservice: /licensing/**