
eureka:
  instance:
    # Register the IP of the service rather than the server name.
    preferIpAddress: true
  client:
    # Register the service with Eureka.
    registerWithEureka: true
    # Pull down a local copy of the registry.
    fetchRegistry: true
    serviceUrl:
        # Location of the Eureka Service
        defaultZone: http://localhost:8761/eureka/

        